### PR TITLE
Feature/upgrade to next 9 4

### PR DESCRIPTION
**Pull request by bbortt**

### CODE REVIEW

**Comment by twhitson** [comment]
@bmealhouse This would be awesome to get in as soon as possible. I'm creating a brand new Next.js application and next-redux-wrapper has been upgraded to work with Next.js 9.3+ so it took me quite a bit of time to track down all the versions that will work together.

For anyone else running into this, next-redux-wrapper 5.0.0 works with next 9.2.2 and next-redux-saga 4.1.2

**Comment by bmealhouse** [comment]
@bbortt @twhitson - I'm way out of the loop on Next.js 9.4 and redux-saga right now, so I don't feel I can give this PR the review that it deserves. I'm also not interested in getting back up to speed on anything redux-saga related.

That being said, maybe the best way forward is to publish a new major version with a beta tag so users (such as @twhitson) can start using this with Next.js 9.4? Then, when you both feel like the changes are solid we can remove the beta tag?

@twhitson - Since you are starting a new project in Next.js 9.4 and next-redux-saga, are you interested in helping out as a maintainer (alongside @bbortt) of this package?

**Comment by bbortt** [comment]
beta release seems fine. will push it later this day.

**Comment by bbortt** [comment]
FYI: Released in [`next-redux-saga@beta`](https://www.npmjs.com/package/next-redux-saga/v/5.0.0-0).

**Pull request merged**
