### PR TITLE
push redux-saga to version 1.0.1.

### PR DESCRIPTION
**Pull request by bbortt**
See #27.

### CODE REVIEW

**Comment by bbortt** [comment]
Oh sure. And I will update the `README.md` in a separate branch.

**Comment by bbortt** [comment]
I'm struggling with the async props @bmealhouse .. Would you mind helping me? :/

**Comment by bmealhouse** [comment]
@bbortt - I will try to take a look over the next day or two. Can you give me access to your fork so I can make commits if necessary?

**Comment by bbortt** [comment]
@bmealhouse That would be great! It should be public.. I haven't declared any rules.

**Comment by bmealhouse** [comment]
@bbortt - It looks like the build is passing now, I will look through the PR and merge if everything looks good.

**Comment by bmealhouse** [comment]
Looks great @bbortt! Thank you again for all your hard work. I will be doing some other cleanup in this repo before v4 release.

**Comment by ezhlobo** [comment]
@bbortt @bmealhouse thank you very much for this 🎉.

@bmealhouse I don't want to bother you, but if you have some approximate estimation for v4 release, could you please share?

**Comment by bmealhouse** [comment]
@all-contributors please add @bbortt for code, question, maintenance, test

**Comment by bmealhouse** [comment]
@ezhlobo - I should be able to have it released sometime tomorrow at the latest.

**Comment by bbortt** [comment]
great DING :) I'm gonna add a note to the `README.md` as well.

**Pull request merged**
