### PR TITLE
Fix rootSaga run conditions (closes #62)

### LINKED ISSUE #62: Running the root saga only once
Hi everyone,
I took a look at #59 and #61. From what I understand, next-redux-wrapper creates three stores per request:

1. On the server: During the app's getInitialProps (the state can be modified here and will be serialized in the end)
2. On the server, during SSR: The state from 1. is used to provide a store for SSR – state changes made during SSR will not be sent to the client, only the serialized state from 1.
3. On the client side using the serialized state from 1.

Let's call the lifetimes of these stores phases and enumerate them as well.

The current solution in the readme modifies the state in phase 1. (`if(!store.getState().saga.ran)`) to remember the saga was run on the server once. The modified state is used in phase 2 (on a different store), which is why `store.getState().saga.ran` is `true` then. This means the rootSaga will not be run in phase 2, which should be perfectly fine as we cannot persistently modify state in phase 2 anyway.  However, the state from phase 1 is also used in phase 3 on the client side, which would lead to the rootSaga not being run on the client-side... :confused:

@bbortt I am wondering if the client-side store actually runs the rootSaga in your setup. Maybe I am getting something wrong here, but as far as I know, the state in phase 3 is the deserialized state from phase 1...

Luckily, within `configureStore` we can take advantage of the second parameter to decide which phase we are in:

```function configureStore(preloadedState, {isServer, req = null}) {```

1. `isServer` is `true` and a request object is provided (`req` is not `null`)
2. `isServer` is `true` and `req` is `null`
3. `isServer` is `false`

Hence, we should be able to achieve the same thing, without adding custom state to the store, like this:

```
  if (req || !isServer) {
    store.sagaTask = sagaMiddleware.run(rootSaga)
  }
```

This works out nicely for me and also runs the saga on the client side.
@bmealhouse @bbortt Is there something I am missing? If not, I would be glad to create a PR for this! :relaxed:

### PR DESCRIPTION
**Pull request by bjoluc**
Updated the README according to #62 and modified the `configure-store.js` test implementation.
Also modified the server tests to pass proper `req` and `isServer` options to `configureStore`.
In order to create a stubbed request I added `jest-express` as a dev dependency.
By the way, jest was trying to generate coverage reports for node_modules and `package.json` – I added an appropriate `coveragePathIgnorePatterns` option to the jest config in `package.json` to fix that.

@bbortt @bmealhouse Agree?

### CODE REVIEW

**Comment by bmealhouse** [comment]
@bbortt - do you think this warrants a breaking version change? or is this something we can just consider minor or patch change?

**Comment by bbortt** [comment]
Minor as `bugfix` imo. I'll try to release it again.

**Comment by bmealhouse** [comment]
Sounds great. Sorry, I haven’t been able to get back to you about the release @bbortt. If it doesn’t work out, I’ll try to get back to you early next week.

**Comment by bjoluc** [comment]
Thanks for the quick response! Nice to hear, you're welcome!

**Comment by bbortt** [comment]
Everything worked fine @bmealhouse, no problem. I just replaced `release` with the npm package `release-it` and pushed all tags.. `v4.1.1` is the latest release.

**Comment by bmealhouse** [comment]
@bbortt - It looks like v4.1.0 is the latest release on npm. We should also create a release in GitHub as well. If possible, it would be good to keep all these (npm, GitHub, and package.json) in sync.

Thank you for getting this published! I’m very fortunate to have your help maintaining this project!

**Comment by bbortt** [comment]
They're completly in sync with the tags.. just not pushed in the correct order. Let me fix this by overwriting `v4.1.1` again ;)

**Comment by bbortt** [comment]
Couldn't overwrite but created patch `4.1.2` which is now the latest. Do you create GitHub releases for patches as well (they're tagged anyways)? `v4.1.0` was released on GitHub.

**Pull request merged**
